### ISSUE TITLE
Crear Link de Pago desde SDK

### ISSUE THREAD

**Issue by lfelipeqn** [epayco/epayco-node#10]
Es posible generar un link de pago desde el SDK de Node?

**Comment by gianfigueroa** [comment]
Yo tambien necesito eso

**Comment by Gerson-epayco** [comment]
Hola feliz día @lfelipeqn @gianfigueroa 

Por ahora no es posible generar Link de pago desde el SDK. Puede usar la integración a través de nuestra API apify https://api.epayco.co/#fdf8fc79-f767-478a-9478-156eca988d8e

Saludos
