### ISSUE TITLE
Validación de tarjeta al momento de crear un Cliente

### ISSUE THREAD

**Issue by jnicolasmarro** [epayco/epayco-node#15]
Requiero saber si con ePayco al momento de crear un cliente y vincularle una tarjeta puedo validar que la tarjeta ingresada sea valida. Haciendo pruebas evidencio que solo me genera error al momento de realizar una transacción.

**Comment by Gerson-epayco** [comment]
Buenos días,

Reciba un cordial saludo @jnicolasmarro 

Le pueden dar una respuesta más clara a esa solicitud en el siguiente link: https://epayco.co/contacto/

Muchas gracias.
