### ISSUE TITLE
EpaycoError clase no definida, rompe el código.

### ISSUE THREAD

**Issue by NeftaliYagua** [epayco/epayco-node#17]
EpaycoError {name: "EpaycoError", message: undefined, stack: "EpaycoError↵    at new Epayco (http://127.0.0.1:80…4:18↵    at http://127.0.0.1:8000/js/app.js:87:10"}
message: undefined
name: "EpaycoError"
stack: "EpaycoError↵    at new Epayco (http://127.0.0.1:8000/js/app.js:13287:15)↵    at Epayco (http://127.0.0.1:8000/js/app.js:13278:16)↵    at Module../resources/js/bootstrap.js (http://127.0.0.1:8000/js/app.js:54967:95)↵    at __webpack_require__ (http://127.0.0.1:8000/js/app.js:20:30)↵    at Object../resources/js/app.js (http://127.0.0.1:8000/js/app.js:54930:1)↵    at __webpack_require__ (http://127.0.0.1:8000/js/app.js:20:30)↵    at Object.0 (http://127.0.0.1:8000/js/app.js:55014:1)↵    at __webpack_require__ (http://127.0.0.1:8000/js/app.js:20:30)↵    at http://127.0.0.1:8000/js/app.js:84:18↵    at http://127.0.0.1:8000/js/app.js:87:10"
__proto__: Error

![Captura de pantalla de 2020-09-15 16-05-03](https://user-images.githubusercontent.com/2866454/93264825-4fc49280-f76d-11ea-8a69-612109fb9b15.png)
![Captura de pantalla de 2020-09-15 16-04-45](https://user-images.githubusercontent.com/2866454/93264841-53581980-f76d-11ea-8710-1675713b3156.png)
![Captura de pantalla de 2020-09-15 16-04-33](https://user-images.githubusercontent.com/2866454/93264842-53f0b000-f76d-11ea-933f-5e1f784fa5c4.png)

**Comment by NeftaliYagua** [comment]
Esta es mi configuración previa:
![Captura de pantalla de 2020-09-15 16-21-16](https://user-images.githubusercontent.com/2866454/93266324-800d3080-f76f-11ea-92f6-5f79e4495aac.png)

**Comment by Gerson-epayco** [comment]
Buen día @NeftaliYagua 

El bug se encuentra solucionado, por favor actualizar el paquete
