### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by johandavidcm** [epayco/epayco-node#22]
Seria increíble que pudiesen añadir el soporte para typescript, sería mucho mejor a la hora de utilizar el paquete.

**Comment by andrefedev** [comment]
Teniendo en cuenta lo pequeña que es está librería no encuentro ninguna razón para que agreguen soporte de tipos si es a eso a lo que te refieres. Si la idea es re-escribir la base del código con Typescript sería innecesario, desde mi humilde opinion esta librería esta muy bien documentada y repito es muy pequeña. Es más tu podrías volver a escribir con Typescrypt o mejor aun con Golang :)
