### ISSUE TITLE
Error CORS Angular

### ISSUE THREAD

**Issue by crorodriguezro** [epayco/epayco-node#3]
Hola, estoy tratando de hacer la petición para tokenizar una tarjeta, la petición la app esta hecha con Ionic(angular). Me esta saliendo el siguiente error: 

`Failed to load https://api.secure.payco.co/v1/tokens: Request header field type is not allowed by Access-Control-Allow-Headers in preflight response.`

Me podrían ayudar por favor?

**Comment by armandozabala** [comment]
Pudiste resolver este problema, a mi me funciona en modo browser pero en el dispositivo no funciona y descubri este error.... @crorodriguezro

**Comment by crorodriguezro** [comment]
Me pasa al contrario, me funciona en el dispositivo pero no en el navegador. Como lo necesito para el dispositivo no seguí investigando @armandozabala

**Comment by armandozabala** [comment]
Woow que bueno que te funcioono, me podria compartir  que hiciste por que mi solucion fue usar el php sdk, instalarlo en un servidor correr esos servicios alli, y desde ionic 3 los invoco como si estuviera consumiendo una REST API, pero el problema lo tuve usando el sdk de node js no me funciona en el dispositivo

**Comment by armandozabala** [comment]
A mi me daba ese error que tienes y la gente de Epayco me dieron todo el soporte, llege a hasta modificar los headers del sdk de nodejs pero ni con eso no logramos funcionar, me dicen que ese sdk de nodejs es para hacer llamado de servidor a servidor, no de frontend a servidor eso fue la explicacion que me dieron, pero si me gustaria saber tu solucion a ver si la logro implementar en mi aplicacion

**Comment by andrew243512** [comment]
> Me pasa al contrario, me funciona en el dispositivo pero no en el navegador. Como lo necesito para el dispositivo no seguí investigando @armandozabala

Podrias por favor decirnos como fue la implementacion o en su defecto compartirnos que hiciste exactamente. Yo tambien tengo el mismo error con este sdk (CORS).

**Comment by crorodriguezro** [comment]
Hola, me dejo de funcionar de nuevo. Ahora me sale un error en el dispositivo. El error es en la linea 50 del archivo index.js. En la linea se hace `if (res.ok) {`. `res` es `undefined` entonces sale el error. 
Antes creo que me habia funcionado por que modifique ese archivo.

Se podria solucionar haciendo fork de la libreria y haciendola compatible con Ionic o haciendo la peticion desde el back.  Aun no se cual de las dos voy a hacer. La del back me gusta por que seria solo copiar lo que tengo del front al back, pero no me gusta la idea de los datos de la tarjeta de credito entrando a mi servidor.

Y el error de CORS sale en los navegadores, siempre va a salir a menos de que ellos modifiquen los headers de la respuesta que ellos envian (no se vale modificar los de la request que hacemos).  Si se prueba en el dispositivo directamente (con la app instalada o con ionic DevApp) el error no sale por que eso es una medida de seguridad de los navegadores .

Siento no haber contestado antes. Cualquier cosa me escriben.  Voy a cerrar el issue por que esta libreria esta hecha para back y no para front.
