### ISSUE TITLE
epayco.customers.delete is not a function

### ISSUE THREAD

**Issue by HumbertoAriza** [epayco/epayco-node#8]
Estoy tratando de eliminar una tarjeta de crédito vinculada a un cliente pero al correr el código de la documentación no funciona.
let delete_customer_info={
    franchise: "visa",
    mask: "000000******0000",
    customer_id:"aca va el customer id"
    }
    epayco.customers.delete(delete_customer_info)
    .then(function(customer) {
        console.log(customer);
    })
    .catch(function(err) {
        console.log("err: " + err);
    });

**Comment by HumbertoAriza** [comment]
epayco.customers.delete(delete_customer_info)
                           ^

TypeError: epayco.customers.delete is not a function

**Comment by pruebasepayco** [comment]
Buenas tardes.

Reciba un cordial saludo.

Informamos  que este es un nuevo método que se ha implementado en la librería del sdk de epayco, por lo tanto debes de actualizarla librería de epayco, puedes clonar tela, utilizar nuevamente el comando $ npm install epayco-node  o implementar este nuevo método se encuentra en la siguiente ruta :https://github.com/epayco/epayco-node/blob/master/lib/resources/customers.js

/**
 * Delete Customer
 *
 * @param {Object} options
 * @api public
 */
customers.prototype.delete = function(options) {
    return this.request('post', "/v1/remove/token", options, sw = false);
};

Estaremos atentos a cualquier novedad, cabe recordar que solo se puede eliminar los token que han sido creados a partir de ayer 19-12-2019
